name: Code Linting

on:
  workflow_dispatch:
  push:
    paths:
      - '**.php'
  pull_request:
    paths:
      - '**.php'

jobs:
  php-code-linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Fix code linting issues
        uses: aglipanci/laravel-pint-action@2.6
        with:
          testMode: true
          configPath: pint.json
